"""Builds data/campus_bank.json — simple college-level questions (EN+TE). Run once; edit & rerun to extend."""
import json, hashlib, pathlib
Q = []
def add(cat, en, te, oen, ote, ans):
    Q.append({"id": "cb" + hashlib.md5(en.encode()).hexdigest()[:8], "cat": cat, "q_en": en, "q_te": te,
              "options_en": oen, "options_te": ote, "answer_index": ans, "difficulty": "easy", "channel": "CAMPUS"})

# ---------------- Telangana & AP basics
add("tsap","What is the capital of Telangana?","తెలంగాణ రాజధాని ఏది?",["Warangal","Hyderabad","Karimnagar","Nizamabad"],["వరంగల్","హైదరాబాద్","కరీంనగర్","నిజామాబాద్"],1)
add("tsap","Telangana was formed in which year?","తెలంగాణ రాష్ట్రం ఏ సంవత్సరంలో ఏర్పడింది?",["2012","2013","2014","2015"],["2012","2013","2014","2015"],2)
add("tsap","Charminar is located in which city?","చార్మినార్ ఏ నగరంలో ఉంది?",["Vijayawada","Hyderabad","Warangal","Tirupati"],["విజయవాడ","హైదరాబాద్","వరంగల్","తిరుపతి"],1)
add("tsap","Which river flows through Vijayawada?","విజయవాడ గుండా ప్రవహించే నది ఏది?",["Godavari","Krishna","Penna","Tungabhadra"],["గోదావరి","కృష్ణా","పెన్నా","తుంగభద్ర"],1)
add("tsap","Tirumala temple is dedicated to which god?","తిరుమల ఆలయం ఏ దేవుడిది?",["Shiva","Venkateswara","Ganesha","Hanuman"],["శివుడు","వెంకటేశ్వరుడు","గణేశుడు","హనుమంతుడు"],1)
add("tsap","Bathukamma is the festival of which state?","బతుకమ్మ ఏ రాష్ట్ర పండుగ?",["Andhra Pradesh","Karnataka","Telangana","Tamil Nadu"],["ఆంధ్రప్రదేశ్","కర్ణాటక","తెలంగాణ","తమిళనాడు"],2)
add("tsap","How many districts does Telangana have (after 2019)?","తెలంగాణలో జిల్లాలు ఎన్ని (2019 తర్వాత)?",["10","23","31","33"],["10","23","31","33"],3)
add("tsap","Which dam is built on the Krishna river near Nalgonda?","నల్గొండ దగ్గర కృష్ణా నదిపై ఉన్న ఆనకట్ట ఏది?",["Srisailam","Nagarjuna Sagar","Polavaram","Jurala"],["శ్రీశైలం","నాగార్జున సాగర్","పోలవరం","జూరాల"],1)
add("tsap","The Thousand Pillar Temple is in which town?","వేయి స్తంభాల గుడి ఏ ఊరిలో ఉంది?",["Hanamkonda","Khammam","Kurnool","Guntur"],["హనుమకొండ","ఖమ్మం","కర్నూలు","గుంటూరు"],0)
add("tsap","Which is the largest city of Andhra Pradesh by population?","జనాభా ప్రకారం ఆంధ్రప్రదేశ్ లో అతిపెద్ద నగరం?",["Vijayawada","Guntur","Visakhapatnam","Nellore"],["విజయవాడ","గుంటూరు","విశాఖపట్నం","నెల్లూరు"],2)
add("tsap","Hussain Sagar lake is in which city?","హుస్సేన్ సాగర్ సరస్సు ఏ నగరంలో ఉంది?",["Hyderabad","Secunderabad only","Warangal","Kakinada"],["హైదరాబాద్","సికింద్రాబాద్ మాత్రమే","వరంగల్","కాకినాడ"],0)
add("tsap","Which is the state bird of Telangana?","తెలంగాణ రాష్ట్ర పక్షి ఏది?",["Peacock","Indian Roller (Palapitta)","Parrot","Sparrow"],["నెమలి","పాలపిట్ట","చిలుక","పిచ్చుక"],1)
add("tsap","Araku Valley is famous for?","అరకు లోయ దేనికి ప్రసిద్ధి?",["Coffee","Cotton","Diamonds","Silk"],["కాఫీ","పత్తి","వజ్రాలు","పట్టు"],0)
add("tsap","Kakatiya dynasty ruled from which capital?","కాకతీయులు ఏ రాజధాని నుంచి పాలించారు?",["Golconda","Warangal","Amaravati","Vijayanagara"],["గోల్కొండ","వరంగల్","అమరావతి","విజయనగరం"],1)
add("tsap","Sri Krishnadevaraya belonged to which empire?","శ్రీకృష్ణదేవరాయలు ఏ సామ్రాజ్యానికి చెందినవారు?",["Kakatiya","Vijayanagara","Mughal","Satavahana"],["కాకతీయ","విజయనగర","మొఘల్","శాతవాహన"],1)
add("tsap","Which is the longest river in Telangana?","తెలంగాణలో అత్యంత పొడవైన నది?",["Krishna","Godavari","Musi","Manjira"],["కృష్ణా","గోదావరి","మూసీ","మంజీరా"],1)
add("tsap","Ramoji Film City is near which city?","రామోజీ ఫిల్మ్ సిటీ ఏ నగరానికి దగ్గరగా ఉంది?",["Hyderabad","Vizag","Tirupati","Vijayawada"],["హైదరాబాద్","వైజాగ్","తిరుపతి","విజయవాడ"],0)
add("tsap","Which Telugu poet wrote 'Maha Prasthanam'?","'మహాప్రస్థానం' రాసిన కవి ఎవరు?",["Gurajada","Sri Sri","Viswanatha","C. Narayana Reddy"],["గురజాడ","శ్రీశ్రీ","విశ్వనాథ","సి. నారాయణరెడ్డి"],1)
add("tsap","Kuchipudi dance belongs to which state?","కూచిపూడి నృత్యం ఏ రాష్ట్రానికి చెందినది?",["Telangana","Andhra Pradesh","Kerala","Odisha"],["తెలంగాణ","ఆంధ్రప్రదేశ్","కేరళ","ఒడిశా"],1)
add("tsap","Which port city is called the 'City of Destiny'?","'సిటీ ఆఫ్ డెస్టినీ' అని పిలిచే నగరం?",["Kakinada","Visakhapatnam","Machilipatnam","Nellore"],["కాకినాడ","విశాఖపట్నం","మచిలీపట్నం","నెల్లూరు"],1)

# ---------------- India basics
add("india","Who is known as the Father of the Nation in India?","భారత జాతిపిత ఎవరు?",["Nehru","Gandhi","Patel","Ambedkar"],["నెహ్రూ","గాంధీ","పటేల్","అంబేద్కర్"],1)
add("india","India's Independence Day is celebrated on?","భారత స్వాతంత్ర్య దినోత్సవం ఎప్పుడు?",["26 January","15 August","2 October","26 November"],["26 జనవరి","15 ఆగస్టు","2 అక్టోబర్","26 నవంబర్"],1)
add("india","National animal of India?","భారత జాతీయ జంతువు?",["Lion","Elephant","Tiger","Leopard"],["సింహం","ఏనుగు","పులి","చిరుత"],2)
add("india","How many states does India have?","భారతదేశంలో రాష్ట్రాలు ఎన్ని?",["25","28","29","30"],["25","28","29","30"],1)
add("india","The Taj Mahal is in which city?","తాజ్ మహల్ ఏ నగరంలో ఉంది?",["Delhi","Jaipur","Agra","Lucknow"],["ఢిల్లీ","జైపూర్","ఆగ్రా","లక్నో"],2)
add("india","Which is the national flower of India?","భారత జాతీయ పుష్పం?",["Rose","Lotus","Jasmine","Sunflower"],["గులాబీ","కమలం","మల్లె","పొద్దుతిరుగుడు"],1)
add("india","Who wrote the Indian national anthem?","భారత జాతీయ గీతం రాసినది ఎవరు?",["Bankim Chandra","Rabindranath Tagore","Sarojini Naidu","Premchand"],["బంకిం చంద్ర","రవీంద్రనాథ్ ఠాగూర్","సరోజినీ నాయుడు","ప్రేమ్‌చంద్"],1)
add("india","Which is the longest river in India?","భారతదేశంలో అత్యంత పొడవైన నది?",["Godavari","Yamuna","Ganga","Brahmaputra"],["గోదావరి","యమునా","గంగా","బ్రహ్మపుత్ర"],2)
add("india","The currency of India is?","భారత కరెన్సీ?",["Dollar","Rupee","Taka","Dinar"],["డాలర్","రూపాయి","టాకా","దీనార్"],1)
add("india","Republic Day is celebrated on?","గణతంత్ర దినోత్సవం ఎప్పుడు?",["15 August","26 January","1 May","14 November"],["15 ఆగస్టు","26 జనవరి","1 మే","14 నవంబర్"],1)
add("india","Who was the first Prime Minister of India?","భారత తొలి ప్రధానమంత్రి ఎవరు?",["Gandhi","Nehru","Patel","Rajendra Prasad"],["గాంధీ","నెహ్రూ","పటేల్","రాజేంద్ర ప్రసాద్"],1)
add("india","The Parliament of India is located in?","భారత పార్లమెంట్ ఎక్కడ ఉంది?",["Mumbai","New Delhi","Kolkata","Chennai"],["ముంబై","న్యూఢిల్లీ","కోల్‌కతా","చెన్నై"],1)
add("india","Which is the highest mountain peak in India?","భారతదేశంలో ఎత్తైన శిఖరం?",["Mount Everest","Kanchenjunga","Nanda Devi","K2"],["ఎవరెస్ట్","కాంచన్‌జంగా","నందా దేవి","K2"],1)
add("india","Children's Day in India is on?","భారతదేశంలో బాలల దినోత్సవం?",["5 September","14 November","2 October","26 January"],["5 సెప్టెంబర్","14 నవంబర్","2 అక్టోబర్","26 జనవరి"],1)
add("india","Teachers' Day (5 Sept) is the birthday of?","ఉపాధ్యాయ దినోత్సవం (సెప్టెంబర్ 5) ఎవరి జయంతి?",["Abdul Kalam","S. Radhakrishnan","Nehru","Tagore"],["అబ్దుల్ కలాం","ఎస్. రాధాకృష్ణన్","నెహ్రూ","ఠాగూర్"],1)
add("india","'Missile Man of India' is?","'భారత మిస్సైల్ మ్యాన్' ఎవరు?",["Homi Bhabha","APJ Abdul Kalam","C.V. Raman","Vikram Sarabhai"],["హోమీ భాభా","ఏపీజే అబ్దుల్ కలాం","సి.వి. రామన్","విక్రమ్ సారాభాయ్"],1)
add("india","Which city is called the Silicon Valley of India?","భారత సిలికాన్ వ్యాలీ అని పిలిచే నగరం?",["Hyderabad","Pune","Bengaluru","Chennai"],["హైదరాబాద్","పూణే","బెంగళూరు","చెన్నై"],2)
add("india","The national sport-like game most associated with India's 1983 World Cup win?","1983 లో భారత్ ప్రపంచ కప్ గెలిచిన ఆట?",["Hockey","Cricket","Football","Kabaddi"],["హాకీ","క్రికెట్","ఫుట్‌బాల్","కబడ్డీ"],1)
add("india","Which Indian state has the largest population?","భారతదేశంలో అత్యధిక జనాభా గల రాష్ట్రం?",["Maharashtra","Bihar","Uttar Pradesh","West Bengal"],["మహారాష్ట్ర","బీహార్","ఉత్తరప్రదేశ్","పశ్చిమ బెంగాల్"],2)
add("india","ISRO headquarters is in?","ఇస్రో ప్రధాన కార్యాలయం ఎక్కడ?",["Hyderabad","Bengaluru","Sriharikota","Thiruvananthapuram"],["హైదరాబాద్","బెంగళూరు","శ్రీహరికోట","తిరువనంతపురం"],1)

# ---------------- Science basics
add("science","Water boils at what temperature (sea level)?","నీరు ఎన్ని డిగ్రీల వద్ద మరుగుతుంది (సముద్ర మట్టం)?",["50°C","90°C","100°C","120°C"],["50°C","90°C","100°C","120°C"],2)
add("science","Which gas do plants absorb from air?","మొక్కలు గాలి నుంచి ఏ వాయువును తీసుకుంటాయి?",["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"],["ఆక్సిజన్","నైట్రోజన్","కార్బన్ డయాక్సైడ్","హైడ్రోజన్"],2)
add("science","The chemical formula of water is?","నీటి రసాయన సూత్రం?",["CO2","H2O","O2","NaCl"],["CO2","H2O","O2","NaCl"],1)
add("science","Which planet is called the Red Planet?","ఎర్ర గ్రహం అని పిలిచే గ్రహం?",["Venus","Mars","Jupiter","Saturn"],["శుక్రుడు","అంగారకుడు","గురుడు","శని"],1)
add("science","How many bones are in the adult human body?","పెద్దవారి శరీరంలో ఎముకలు ఎన్ని?",["106","206","306","150"],["106","206","306","150"],1)
add("science","Which organ pumps blood in the body?","శరీరంలో రక్తాన్ని పంప్ చేసే అవయవం?",["Lungs","Liver","Heart","Kidney"],["ఊపిరితిత్తులు","కాలేయం","గుండె","మూత్రపిండం"],2)
add("science","The largest planet in our solar system?","సౌర కుటుంబంలో అతిపెద్ద గ్రహం?",["Earth","Saturn","Jupiter","Neptune"],["భూమి","శని","గురుడు","నెప్ట్యూన్"],2)
add("science","Which vitamin do we get from sunlight?","సూర్యరశ్మి నుంచి మనకు లభించే విటమిన్?",["A","B","C","D"],["A","B","C","D"],3)
add("science","Sound cannot travel through?","శబ్దం దేని గుండా ప్రయాణించదు?",["Air","Water","Steel","Vacuum"],["గాలి","నీరు","ఉక్కు","శూన్యం"],3)
add("science","Which blood group is the universal donor?","యూనివర్సల్ డోనర్ రక్త వర్గం?",["A+","B+","AB+","O-"],["A+","B+","AB+","O-"],3)
add("science","The hardest natural substance is?","అత్యంత గట్టి సహజ పదార్థం?",["Gold","Iron","Diamond","Granite"],["బంగారం","ఇనుము","వజ్రం","గ్రానైట్"],2)
add("science","Which gas do humans need to breathe?","మనుషులు శ్వాసకు ఏ వాయువు అవసరం?",["Carbon dioxide","Oxygen","Nitrogen","Helium"],["కార్బన్ డయాక్సైడ్","ఆక్సిజన్","నైట్రోజన్","హీలియం"],1)
add("science","Light travels fastest in?","కాంతి దేనిలో వేగంగా ప్రయాణిస్తుంది?",["Water","Glass","Vacuum","Air"],["నీరు","గాజు","శూన్యం","గాలి"],2)
add("science","The unit of electric current is?","విద్యుత్ ప్రవాహ యూనిట్?",["Volt","Watt","Ampere","Ohm"],["వోల్ట్","వాట్","ఆంపియర్","ఓమ్"],2)
add("science","Which is the closest star to Earth?","భూమికి అత్యంత దగ్గరి నక్షత్రం?",["Moon","Sun","Sirius","Polaris"],["చంద్రుడు","సూర్యుడు","సిరియస్","ధ్రువ నక్షత్రం"],1)
add("science","Plants make food by which process?","మొక్కలు ఆహారం తయారు చేసే ప్రక్రియ?",["Respiration","Digestion","Photosynthesis","Evaporation"],["శ్వాసక్రియ","జీర్ణక్రియ","కిరణజన్య సంయోగక్రియ","బాష్పీభవనం"],2)
add("science","Which metal is liquid at room temperature?","గది ఉష్ణోగ్రత వద్ద ద్రవంగా ఉండే లోహం?",["Iron","Mercury","Copper","Silver"],["ఇనుము","పాదరసం","రాగి","వెండి"],1)
add("science","How many teeth does an adult human normally have?","పెద్దవారికి సాధారణంగా ఎన్ని పళ్ళు ఉంటాయి?",["28","30","32","36"],["28","30","32","36"],2)
add("science","The Earth takes how long to go around the Sun?","భూమి సూర్యుని చుట్టూ తిరగడానికి ఎంత సమయం?",["1 day","1 month","1 year","10 years"],["1 రోజు","1 నెల","1 సంవత్సరం","10 సంవత్సరాలు"],2)
add("science","Which part of the plant conducts photosynthesis mainly?","మొక్కలో ప్రధానంగా ఆహారం తయారు చేసే భాగం?",["Root","Stem","Leaf","Flower"],["వేరు","కాండం","ఆకు","పువ్వు"],2)

# ---------------- Computers & tech (college life)
add("tech","What does 'WWW' stand for?","'WWW' అంటే?",["World Wide Web","World Web Wide","Web World Wide","Wide World Web"],["World Wide Web","World Web Wide","Web World Wide","Wide World Web"],0)
add("tech","Which company makes the Android operating system?","ఆండ్రాయిడ్ ఆపరేటింగ్ సిస్టమ్ ఎవరిది?",["Apple","Microsoft","Google","Samsung"],["ఆపిల్","మైక్రోసాఫ్ట్","గూగుల్","శాంసంగ్"],2)
add("tech","'CPU' stands for?","'CPU' పూర్తి రూపం?",["Central Processing Unit","Computer Personal Unit","Central Program Utility","Control Processing Unit"],["Central Processing Unit","Computer Personal Unit","Central Program Utility","Control Processing Unit"],0)
add("tech","Which of these is NOT a programming language?","వీటిలో ప్రోగ్రామింగ్ భాష కానిది?",["Python","Java","HTML5 Photoshop","C++"],["Python","Java","HTML5 Photoshop","C++"],2)
add("tech","Who founded Microsoft?","మైక్రోసాఫ్ట్ స్థాపకుడు?",["Steve Jobs","Bill Gates","Elon Musk","Mark Zuckerberg"],["స్టీవ్ జాబ్స్","బిల్ గేట్స్","ఎలాన్ మస్క్","మార్క్ జుకర్‌బర్గ్"],1)
add("tech","1 GB equals how many MB?","1 GB = ఎన్ని MB?",["100","512","1024","2048"],["100","512","1024","2048"],2)
add("tech","Which key combination is used to copy in Windows?","విండోస్ లో కాపీ చేయడానికి కీలు?",["Ctrl+V","Ctrl+C","Ctrl+X","Ctrl+Z"],["Ctrl+V","Ctrl+C","Ctrl+X","Ctrl+Z"],1)
add("tech","UPI is used for?","UPI దేనికి ఉపయోగిస్తారు?",["Watching videos","Digital payments","Playing games","Sending emails"],["వీడియోలు చూడటానికి","డిజిటల్ చెల్లింపులకు","ఆటలకు","ఇమెయిల్ కి"],1)
add("tech","The brain of the computer is?","కంప్యూటర్ మెదడు అని దేన్ని అంటారు?",["Monitor","Keyboard","CPU","Mouse"],["మానిటర్","కీబోర్డ్","CPU","మౌస్"],2)
add("tech","Which company owns WhatsApp and Instagram?","వాట్సాప్, ఇన్‌స్టాగ్రామ్ ఎవరి సొంతం?",["Google","Meta","Apple","Amazon"],["గూగుల్","మెటా","ఆపిల్","అమెజాన్"],1)
add("tech","'AI' stands for?","'AI' అంటే?",["Auto Internet","Artificial Intelligence","Advanced Input","Applied Information"],["Auto Internet","Artificial Intelligence","Advanced Input","Applied Information"],1)
add("tech","Which of these is an input device?","వీటిలో ఇన్‌పుట్ పరికరం?",["Printer","Speaker","Keyboard","Monitor"],["ప్రింటర్","స్పీకర్","కీబోర్డ్","మానిటర్"],2)
add("tech","'PDF' stands for?","'PDF' పూర్తి రూపం?",["Portable Document Format","Personal Data File","Print Document Form","Public Data Format"],["Portable Document Format","Personal Data File","Print Document Form","Public Data Format"],0)
add("tech","Which search engine is the most used in the world?","ప్రపంచంలో ఎక్కువగా వాడే సెర్చ్ ఇంజిన్?",["Bing","Yahoo","Google","DuckDuckGo"],["బింగ్","యాహూ","గూగుల్","డక్‌డక్‌గో"],2)
add("tech","Aadhaar is issued by?","ఆధార్ జారీ చేసేది?",["RBI","UIDAI","SEBI","NITI Aayog"],["RBI","UIDAI","SEBI","నీతి ఆయోగ్"],1)

# ---------------- Simple maths & logic
add("logic","What is 15% of 200?","200 లో 15% ఎంత?",["20","25","30","35"],["20","25","30","35"],2)
add("logic","Next number: 2, 4, 8, 16, ?","తర్వాతి సంఖ్య: 2, 4, 8, 16, ?",["18","24","32","64"],["18","24","32","64"],2)
add("logic","If today is Monday, what day is it after 10 days?","ఈరోజు సోమవారం అయితే 10 రోజుల తర్వాత ఏ వారం?",["Wednesday","Thursday","Friday","Saturday"],["బుధవారం","గురువారం","శుక్రవారం","శనివారం"],1)
add("logic","A shirt costs ₹500 with 20% discount. Price?","₹500 షర్ట్ పై 20% డిస్కౌంట్. ధర?",["₹380","₹400","₹420","₹450"],["₹380","₹400","₹420","₹450"],1)
add("logic","Square root of 144?","144 వర్గమూలం?",["10","11","12","14"],["10","11","12","14"],2)
add("logic","Odd one out: Apple, Banana, Carrot, Mango","భిన్నమైనది: ఆపిల్, అరటి, క్యారెట్, మామిడి",["Apple","Banana","Carrot","Mango"],["ఆపిల్","అరటి","క్యారెట్","మామిడి"],2)
add("logic","Average of 10, 20 and 30?","10, 20, 30 సగటు?",["15","20","25","30"],["15","20","25","30"],1)
add("logic","Next letter: A, C, E, G, ?","తర్వాతి అక్షరం: A, C, E, G, ?",["H","I","J","K"],["H","I","J","K"],1)
add("logic","How many minutes are in 2.5 hours?","2.5 గంటల్లో ఎన్ని నిమిషాలు?",["120","130","150","180"],["120","130","150","180"],2)
add("logic","If 5 pens cost ₹40, cost of 8 pens?","5 పెన్నులు ₹40 అయితే 8 పెన్నుల ధర?",["₹56","₹60","₹64","₹72"],["₹56","₹60","₹64","₹72"],2)
add("logic","Which number is a prime?","ప్రధాన సంఖ్య ఏది?",["9","15","17","21"],["9","15","17","21"],2)
add("logic","Rahul is taller than Sita; Sita is taller than Ravi. Shortest?","రాహుల్ సీత కంటే పొడవు; సీత రవి కంటే పొడవు. పొట్టివారు?",["Rahul","Sita","Ravi","Can't say"],["రాహుల్","సీత","రవి","చెప్పలేం"],2)
add("logic","Face south, turn left. Which direction now?","దక్షిణానికి చూస్తూ ఎడమకు తిరిగితే ఏ దిక్కు?",["North","East","West","South"],["ఉత్తరం","తూర్పు","పడమర","దక్షిణం"],1)
add("logic","Which is bigger: 3/4 or 2/3?","ఏది పెద్దది: 3/4 లేదా 2/3?",["3/4","2/3","Equal","Can't say"],["3/4","2/3","సమానం","చెప్పలేం"],0)
add("logic","Clock shows 3:00. Angle between hands?","గడియారంలో 3:00. ముళ్ళ మధ్య కోణం?",["45°","60°","90°","120°"],["45°","60°","90°","120°"],2)
add("logic","Sum of angles of a triangle?","త్రిభుజం కోణాల మొత్తం?",["90°","180°","270°","360°"],["90°","180°","270°","360°"],1)
add("logic","20 students, 40% girls. Boys?","20 మంది విద్యార్థుల్లో 40% అమ్మాయిలు. అబ్బాయిలు?",["8","10","12","14"],["8","10","12","14"],2)
add("logic","Which comes next: Mon, Wed, Fri, ?","తర్వాత ఏది: సోమ, బుధ, శుక్ర, ?",["Sat","Sun","Mon","Tue"],["శని","ఆది","సోమ","మంగళ"],1)
add("logic","Simple interest on ₹1000 at 10% for 1 year?","₹1000 పై 10% వడ్డీతో 1 సంవత్సరం సాధారణ వడ్డీ?",["₹10","₹50","₹100","₹110"],["₹10","₹50","₹100","₹110"],2)
add("logic","Double of half of 50?","50 లో సగానికి రెట్టింపు?",["25","50","75","100"],["25","50","75","100"],1)

# ---------------- Simple English
add("english","Opposite of 'Happy'?","'Happy' కి వ్యతిరేక పదం?",["Glad","Sad","Joyful","Cheerful"],["Glad","Sad","Joyful","Cheerful"],1)
add("english","Plural of 'Child'?","'Child' బహువచనం?",["Childs","Children","Childrens","Childes"],["Childs","Children","Childrens","Childes"],1)
add("english","Choose the correct spelling.","సరైన స్పెల్లింగ్ ఎంచుకోండి.",["Recieve","Receive","Receeve","Riceive"],["Recieve","Receive","Receeve","Riceive"],1)
add("english","Synonym of 'Big'?","'Big' కి సమానార్థక పదం?",["Tiny","Large","Small","Short"],["Tiny","Large","Small","Short"],1)
add("english","She ___ to college every day.","She ___ to college every day.",["go","goes","going","gone"],["go","goes","going","gone"],1)
add("english","Past tense of 'Eat'?","'Eat' భూతకాలం?",["Eated","Ate","Eaten","Eats"],["Eated","Ate","Eaten","Eats"],1)
add("english","Which is a noun?","వీటిలో నామవాచకం?",["Run","Quickly","Book","Beautiful"],["Run","Quickly","Book","Beautiful"],2)
add("english","'Once in a blue moon' means?","'Once in a blue moon' అర్థం?",["Every night","Very rarely","Always","Never"],["ప్రతి రాత్రి","చాలా అరుదుగా","ఎప్పుడూ","ఎప్పటికీ కాదు"],1)
add("english","Choose the correct article: ___ apple a day.","సరైన article: ___ apple a day.",["A","An","The","No article"],["A","An","The","No article"],1)
add("english","Opposite of 'Ancient'?","'Ancient' వ్యతిరేకం?",["Old","Modern","Historic","Past"],["Old","Modern","Historic","Past"],1)
add("english","Fill: I have been waiting ___ 2 hours.","పూరించండి: I have been waiting ___ 2 hours.",["since","for","from","at"],["since","for","from","at"],1)
add("english","Which word is spelled correctly?","సరైన స్పెల్లింగ్?",["Definately","Definitely","Definitly","Defenitely"],["Definately","Definitely","Definitly","Defenitely"],1)
add("english","'Bring the house down' means?","'Bring the house down' అర్థం?",["Destroy a house","Get loud applause","Sell a house","Clean a house"],["ఇల్లు కూల్చడం","పెద్ద చప్పట్లు పొందడం","ఇల్లు అమ్మడం","ఇల్లు శుభ్రం చేయడం"],1)
add("english","One who writes books is a?","పుస్తకాలు రాసే వ్యక్తి?",["Editor","Author","Reader","Printer"],["Editor","Author","Reader","Printer"],1)
add("english","Choose correct: He is ___ than me.","సరైనది: He is ___ than me.",["tall","taller","tallest","more tall"],["tall","taller","tallest","more tall"],1)

# ---------------- Sports, movies, general fun
add("fun","How many players in a cricket team on the field?","క్రికెట్ జట్టులో మైదానంలో ఎంతమంది ఆటగాళ్ళు?",["9","10","11","12"],["9","10","11","12"],2)
add("fun","Olympic Games are held every ___ years.","ఒలింపిక్ క్రీడలు ప్రతి ___ సంవత్సరాలకు జరుగుతాయి.",["2","3","4","5"],["2","3","4","5"],2)
add("fun","'Baahubali' was directed by?","'బాహుబలి' దర్శకుడు?",["Trivikram","S.S. Rajamouli","Sukumar","Koratala Siva"],["త్రివిక్రమ్","ఎస్.ఎస్. రాజమౌళి","సుకుమార్","కొరటాల శివ"],1)
add("fun","Which song from RRR won an Oscar?","RRR లో ఆస్కార్ గెలిచిన పాట?",["Dosti","Naatu Naatu","Komuram Bheemudo","Etthara Jenda"],["దోస్తీ","నాటు నాటు","కొమురం భీముడో","ఎత్తర జెండా"],1)
add("fun","P.V. Sindhu plays which sport?","పి.వి. సింధు ఆడే క్రీడ?",["Tennis","Badminton","Chess","Hockey"],["టెన్నిస్","బ్యాడ్మింటన్","చెస్","హాకీ"],1)
add("fun","Which is the largest ocean?","అతిపెద్ద మహాసముద్రం?",["Atlantic","Indian","Pacific","Arctic"],["అట్లాంటిక్","హిందూ","పసిఫిక్","ఆర్కిటిక్"],2)
add("fun","How many colours in a rainbow?","ఇంద్రధనుస్సులో ఎన్ని రంగులు?",["5","6","7","8"],["5","6","7","8"],2)
add("fun","Which country is called the Land of the Rising Sun?","ఉదయించే సూర్యుని దేశం?",["China","Japan","Korea","Thailand"],["చైనా","జపాన్","కొరియా","థాయిలాండ్"],1)
add("fun","In chess, which piece can only move diagonally?","చెస్ లో వికర్ణంగా మాత్రమే కదిలే పావు?",["Rook","Knight","Bishop","King"],["రూక్","నైట్","బిషప్","కింగ్"],2)
add("fun","Which is the smallest continent?","అతి చిన్న ఖండం?",["Europe","Australia","Antarctica","South America"],["యూరప్","ఆస్ట్రేలియా","అంటార్కిటికా","దక్షిణ అమెరికా"],1)
add("fun","Sachin Tendulkar is famous in which sport?","సచిన్ టెండూల్కర్ ఏ క్రీడలో ప్రసిద్ధుడు?",["Hockey","Cricket","Football","Kabaddi"],["హాకీ","క్రికెట్","ఫుట్‌బాల్","కబడ్డీ"],1)
add("fun","Which is the tallest animal?","అత్యంత ఎత్తైన జంతువు?",["Elephant","Giraffe","Camel","Horse"],["ఏనుగు","జిరాఫీ","ఒంటె","గుర్రం"],1)
add("fun","Capital of the USA?","అమెరికా (USA) రాజధాని?",["New York","Washington D.C.","Los Angeles","Chicago"],["న్యూయార్క్","వాషింగ్టన్ డి.సి.","లాస్ ఏంజెలెస్","చికాగో"],1)
add("fun","How many days in a leap year?","లీప్ సంవత్సరంలో ఎన్ని రోజులు?",["364","365","366","367"],["364","365","366","367"],2)
add("fun","Which festival is called the festival of lights?","దీపాల పండుగ అని పిలిచేది?",["Holi","Diwali","Sankranti","Ugadi"],["హోళీ","దీపావళి","సంక్రాంతి","ఉగాది"],1)
add("fun","The Telugu New Year festival is?","తెలుగు నూతన సంవత్సర పండుగ?",["Sankranti","Ugadi","Dasara","Diwali"],["సంక్రాంతి","ఉగాది","దసరా","దీపావళి"],1)
add("fun","FIFA World Cup is for which sport?","ఫిఫా ప్రపంచ కప్ ఏ క్రీడకు?",["Cricket","Football","Hockey","Tennis"],["క్రికెట్","ఫుట్‌బాల్","హాకీ","టెన్నిస్"],1)
add("fun","Which animal is known as the 'Ship of the Desert'?","'ఎడారి ఓడ' అని పిలిచే జంతువు?",["Horse","Camel","Elephant","Donkey"],["గుర్రం","ఒంటె","ఏనుగు","గాడిద"],1)
add("fun","How many zeros in one lakh?","ఒక లక్షలో ఎన్ని సున్నాలు?",["4","5","6","7"],["4","5","6","7"],1)
add("fun","Neeraj Chopra won Olympic gold in?","నీరజ్ చోప్రా ఒలింపిక్ బంగారు పతకం ఏ క్రీడలో?",["Shooting","Javelin throw","Wrestling","Boxing"],["షూటింగ్","జావెలిన్ త్రో","రెజ్లింగ్","బాక్సింగ్"],1)

# ---------------- Career / life skills (useful for degree students)
add("career","What does 'CV' in job applications stand for?","ఉద్యోగ దరఖాస్తుల్లో 'CV' అంటే?",["Curriculum Vitae","Career Value","Certified Verification","Company Visit"],["Curriculum Vitae","Career Value","Certified Verification","Company Visit"],0)
add("career","What is the minimum age to vote in India?","భారతదేశంలో ఓటు వేయడానికి కనీస వయస్సు?",["16","18","21","25"],["16","18","21","25"],1)
add("career","PAN card is mainly used for?","పాన్ కార్డ్ ప్రధానంగా దేనికి?",["Driving","Income tax / finance","Passport","Voting"],["డ్రైవింగ్","ఆదాయపు పన్ను / ఆర్థిక","పాస్‌పోర్ట్","ఓటింగ్"],1)
add("career","A 'savings account' is opened at a?","'సేవింగ్స్ ఖాతా' ఎక్కడ తెరుస్తారు?",["Post office only","Bank","School","Police station"],["పోస్టాఫీసు మాత్రమే","బ్యాంక్","పాఠశాల","పోలీస్ స్టేషన్"],1)
add("career","Which exam is for engineering admission in TS/AP?","TS/AP లో ఇంజినీరింగ్ ప్రవేశానికి పరీక్ష?",["NEET","EAPCET","CAT","GATE"],["NEET","EAPCET","CAT","GATE"],1)
add("career","Emergency number in India for police/ambulance?","భారత అత్యవసర నంబర్ (పోలీస్/అంబులెన్స్)?",["100 only","112","911","108 only"],["100 మాత్రమే","112","911","108 మాత్రమే"],1)
add("career","Which exam do you write to become a bank PO?","బ్యాంక్ PO కావడానికి రాసే పరీక్ష?",["IBPS PO","UPSC CSE","NEET","JEE"],["IBPS PO","UPSC CSE","NEET","JEE"],0)
add("career","'Group 2' exam in Telangana is conducted by?","తెలంగాణలో 'గ్రూప్ 2' పరీక్ష నిర్వహించేది?",["UPSC","TSPSC","SSC","RRB"],["UPSC","TSPSC","SSC","RRB"],1)
add("career","Which document proves your date of birth commonly?","పుట్టిన తేదీకి సాధారణ రుజువు?",["Ration card","10th class certificate","Bus pass","Library card"],["రేషన్ కార్డు","10వ తరగతి సర్టిఫికెట్","బస్ పాస్","లైబ్రరీ కార్డు"],1)
add("career","Which skill is most asked in interviews?","ఇంటర్వ్యూలలో ఎక్కువగా అడిగే నైపుణ్యం?",["Communication","Swimming","Cooking","Driving"],["కమ్యూనికేషన్","ఈత","వంట","డ్రైవింగ్"],0)

ids = {q["id"] for q in Q}
assert len(ids) == len(Q), "dup id"
for q in Q:
    assert len(q["options_en"]) == 4 == len(q["options_te"]) and 0 <= q["answer_index"] < 4, q
out = pathlib.Path(__file__).resolve().parents[2] / "data" / "campus_bank.json"
out.write_text(json.dumps(Q, ensure_ascii=False, indent=1), encoding="utf-8")
print(len(Q), "questions ->", out)
